# Generated by Django 2.2.4 on 2019-08-19 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190819_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 17, 25, 16, 23701, tzinfo=utc)),
        ),
    ]
